# Generated by Django 4.2.20 on 2025-03-25 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarakterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleValuesForHarak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('harakter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.haraktername')),
            ],
        ),
        migrations.CreateModel(
            name='ValueForJanrInstrumentHarak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harakter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.haraktername')),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.instrument')),
                ('janr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.janr')),
                ('value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.possiblevaluesforharak')),
            ],
        ),
        migrations.CreateModel(
            name='JanrInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.instrument')),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.janr')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentsHarakter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harakter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.haraktername')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.instrument')),
            ],
        ),
    ]
