# Generated by Django 5.1.6 on 2025-04-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onotology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haraktername',
            options={'verbose_name': 'название характеристики', 'verbose_name_plural': 'Название Характеристик'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AlterModelOptions(
            name='instrumentsharakter',
            options={'verbose_name': 'характеристика для инструмента', 'verbose_name_plural': 'Характеристики для инструмента'},
        ),
        migrations.AlterModelOptions(
            name='janr',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='janrinstruments',
            options={'verbose_name': 'инструмент для жанра', 'verbose_name_plural': 'Инструменты для жанра'},
        ),
        migrations.AlterModelOptions(
            name='possiblevaluesforharak',
            options={'verbose_name': 'значения для характеристики', 'verbose_name_plural': 'Значения для характеристик'},
        ),
        migrations.RemoveField(
            model_name='valueforjanrinstrumentharak',
            name='harakter_id',
        ),
        migrations.AlterField(
            model_name='valueforjanrinstrumentharak',
            name='instrument_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onotology.instrumentsharakter'),
        ),
        migrations.AlterField(
            model_name='valueforjanrinstrumentharak',
            name='janr_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onotology.janrinstruments'),
        ),
        migrations.AlterField(
            model_name='valueforjanrinstrumentharak',
            name='value_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onotology.possiblevaluesforharak'),
        ),
    ]
