# Generated by Django 5.1.6 on 2025-04-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onotology', '0002_alter_haraktername_options_alter_instrument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valueforjanrinstrumentharak',
            options={'verbose_name': 'значение характеристики для жанра', 'verbose_name_plural': 'Значения характеристик для жанра'},
        ),
        migrations.CreateModel(
            name='TableForFormCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harakter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.haraktername')),
                ('instrument_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onotology.instrumentsharakter')),
                ('value_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onotology.possiblevaluesforharak')),
            ],
        ),
    ]
