# Generated by Django 5.1.6 on 2025-04-10 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onotology', '0003_alter_valueforjanrinstrumentharak_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableforformcheck',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.instrument'),
        ),
        migrations.AlterField(
            model_name='tableforformcheck',
            name='value_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.possiblevaluesforharak'),
        ),
        migrations.AlterField(
            model_name='valueforjanrinstrumentharak',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.instrumentsharakter'),
        ),
        migrations.AlterField(
            model_name='valueforjanrinstrumentharak',
            name='janr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.janrinstruments'),
        ),
        migrations.AlterField(
            model_name='valueforjanrinstrumentharak',
            name='value_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onotology.possiblevaluesforharak'),
        ),
        migrations.AlterUniqueTogether(
            name='valueforjanrinstrumentharak',
            unique_together={('janr_id', 'instrument_id', 'value_id')},
        ),
    ]
