# Generated by Django 5.1.6 on 2025-04-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onotology', '0004_alter_tableforformcheck_instrument_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tableforformcheck',
            unique_together={('harakter', 'instrument_id', 'value_id')},
        ),
    ]
