# Generated by Django 5.1.6 on 2025-04-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onotology', '0005_alter_tableforformcheck_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrumentsharakter',
            unique_together={('instrument', 'harakter')},
        ),
        migrations.AlterUniqueTogether(
            name='janrinstruments',
            unique_together={('instrument', 'janr')},
        ),
    ]
